---
name: sample-app-ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install-dependencies
        run: npm install ci
      - name: start-server
        run: |
          npm run mongo:start & sleep 5
          npm ci-start & sleep 5
      - name: run-tests
        run: npm run test
      - name: pack
        run: npm pack
