---
name: ta-ci-example
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install-dependencies
        run: npm install ci
      
      - name: run-tests
        run: npm run unit-tests
      
      - name: package
        run: npm pack
