---
name: sample-app-ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install-dependencies
        run: npm install ci

      - name: start-server
        run: |
          npm run mongo:start
          npm run ci-start

      - name: run-tests
        run: npm run test

      - name: pack
        run: npm pack
